#!/bin/bash
if [ \( $# -eq 1 \) ]; then {
	sudo pgrep -u "$1" >/dev/null
		if [ $? -eq 0 ]; then {
			sudo passwd -l "$1" >/dev/null
			sudo apt-get install psmisc >/dev/null
			sudo killall -KILL -u "$1" >/dev/null
			sudo userdel "$1" >/dev/null
			echo "$1"" successfully deleted."
		}
		else
			echo "The user ""$1"" isn't logged in."
		fi
}
else
	echo "One valid file name expected.";
fi
